## Numpy practice
Resource: http://cs231n.github.io/python-numpy-tutorial/#numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
print (type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(3,)


In [8]:
print(a[0]) # index the array

1


In [7]:
print(a[1],a[2])

2 3


In [9]:
# change element of the array
a[0] = 5

In [10]:
print(a)

[5 2 3]


In [11]:
a

array([5, 2, 3])

In [12]:
b = np.array([[1,2,3],
             [4,5,6]])

In [13]:
b.shape

(2, 3)

In [15]:
b[0, 0] # index upper left element

1

In [16]:
print(b[0,0], b[0,1], b[1,0])

1 2 4


In [17]:
## Use numpy to create arrays

# Create an array of all zeros
# Prints "[[ 0.  0.]
#          [ 0.  0.]]"

a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [18]:
b = np.ones((1,2)) # Create an array of all ones
b      # Prints "[[ 1.  1.]]"

array([[1., 1.]])

In [19]:
# build a 2x2 array filled with constant, 7.
c = np.full((2,2), 7)
c

array([[7, 7],
       [7, 7]])

In [20]:
# create identiny matrix of nxn 
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [ ]:
# create an array of random values
# could use for initializing weights for NN!

e = np.random.random((2,2))
e

## Array indexing 

In [21]:
# slicing: similarrly to lists, but we need to specify a
# slice for each dimensison of the array

In [22]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
# Use slicing to pull out the subarray of the first 2 rows and columns 1,2

b = a[:2, 1:3] # slice of a
b

array([[2, 3],
       [6, 7]])

In [ ]:
# could be used for minors/determinants?

In [25]:
# Note: a slice of an array is a vew into the same data,
# modifiying a slice will modify the original array.

print(a[0,1])

2


In [26]:
b[0,0]

2

In [27]:
b[0,0] = 77

In [28]:
print(a) # we see the value is updated

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
a = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
# Two ways of accessing data in the middle row of an array:
# 1. Mixing integer indexing with slices yields an array of lower rank,
# 2. Only slices yields an array of the same rank as the original

row_r1 = a[1, :] # Rank 1 view of the second row of a

In [31]:
row_r1

array([5, 6, 7, 8])

In [32]:
row_r2 = a[1:2, :] # rank 2 view of the second row of a
row_r2

array([[5, 6, 7, 8]])

In [33]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing:**
<br>
When you index into numpy arays using slicing, the resulting array view will always be a subarray of the original array.
<br>
In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array!

In [34]:
a = np.array([[1,2],[3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
# An example of integer array indexing.
# The returned array will habe shape (3,) and
print(a[[0,1,2], [0,1,0]]) # why does this work? 

[1 4 5]


In [42]:
a[[0,1,2], [1,1,1]] # Row index, col index

array([2, 4, 6])

In [43]:
# When using integer array indexing, you can reuse the same
# element from the source array: 

print(a[[0,0], [1,1]])

[2 2]


# useful trick with integer array indexing
### Selecting or mutation one element from each row of a matrix

In [55]:
import numpy as np 

# create a new array
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9],
              [10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [56]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

In [57]:
b

array([0, 2, 0, 1])

In [58]:
np.arange(4)

array([0, 1, 2, 3])

In [59]:
# Select one element from each row of a, using the indices in b
print(a[np.arange(4), b])

[ 1  6  7 11]


In [60]:
# Mutate one element from each row of a uisng the indecies in b
a[np.arange(4), b] += 10
# add 10 to each of the elements 

In [61]:
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

### Boolean array indexing: 
<br>
<br>
Boolean array indexing lest us pick out arbitrary elements of an array.
Frequently this type of indexing is used to select the elements of an array that 
satisfy some condition.
<br>
<br>
could be useful for getting values from q-tables? 

In [63]:
a = np.array([[1, 2],
            [3, 4],
            [5,6]])

In [64]:
bool_idx = (a > 2) # Find the elements of a that are bigger than 2.

#this returns a numpy array of bools of the same 
# shape as a, where each slot of book_idx tells 
# wheter that element of a is > 2.

print(bool_idx) 

[[False False]
 [ True  True]
 [ True  True]]


In [65]:
# we can use bool array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx

print(a[bool_idx])

[3 4 5 6]


In [66]:
# we can do all of the above with a concise statement:
print(a[a>2])

[3 4 5 6]


In [67]:
# ^cool!

# Datatypes 
<br>
<br>
1.  Every numpy array is a grid of elements of the same type.
<br>
2. Numpy provides a large set of numeric datatypes that you can use to construct arrays.
<br>
3. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. 

In [69]:
x = np.array([1, 2]) # let numpy choose the datatype
x.dtype

dtype('int64')

In [71]:
x = np.array([1.0,2.0]) # let numpy choose agian
x.dtype

dtype('float64')

In [72]:
x = np.array([1, 2], dtype=np.int64) # forces int
x.dtype

dtype('int64')

### Array math
<br>
Basic math functions operate elementwise on arrays,
and are available both as operatior overloads
and as functions in the numpy module:

In [73]:
x = np.array([[1,2],
             [3,4]], dtype=np.float64)

y = np.array([[5,6],
             [7,8]], dtype=np.float64)


In [74]:
# Elementwise sum; both produce the array
x + y 

array([[ 6.,  8.],
       [10., 12.]])

In [75]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [77]:
# Eleent wise difference; both produce the array
# method 1 

x - y

array([[-4., -4.],
       [-4., -4.]])

In [78]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [79]:
# Elementwise product; both produce the array
x * y

array([[ 5., 12.],
       [21., 32.]])

In [80]:
np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [81]:
# Elementwise division; 
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [82]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [83]:
# Elementwise square root; 
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

### NOTE: `*` is elementwise multiplication, not matrix multiplication
Instead use the `dot` function to compute: 
    - inner producs of vectors
    - to multiply a vector by a matrix
    - to multiply matrices
<br>
<br>
 dot is available both as a function in the numpy module and as an instance method of array objects:   

In [85]:
x = np.array([[1,2],
             [3,4]])
y = np.array([[5,6],
             [7,8]])

In [86]:
v = np.array([9, 10])
w = np.array([11, 12])

In [87]:
# Inner product of vectors, both produce 219
v.dot(w)

219

In [88]:
np.dot(v, w)

219

In [89]:
# matrix / vector product; both produce the rank 1 array [29 67]

x.dot(v)

array([29, 67])

In [90]:
np.dot(x, v)

array([29, 67])

In [92]:
# Matrix / matrix product; both produce the same rank 2 array
x.dot(y)

array([[19, 22],
       [43, 50]])

In [93]:
np.dot(x, y)

array([[19, 22],
       [43, 50]])

### Numpy provides many useful functions for preforming computations on arrays;
<br>
one of the most useful is `np.sum`

In [96]:
x = np.array([[1,2],
             [3,4]])


In [97]:
# compute sum of all elements
np.sum(x)

10

In [98]:
# Compute sum of each column
np.sum(x, axis=0)

array([4, 6])

In [99]:
# Compute sum of each row
np.sum(x, axis=1)

array([3, 7])

Frequently we need to reshape or manipulate data in arrays. 
The simplets example is transposing a matrix. <br>
<br>
To transpose a matrix use `T` attribute of an array object

In [101]:
print(x)

[[1 2]
 [3 4]]


In [102]:
x.T

array([[1, 3],
       [2, 4]])

In [103]:
# Note: taking the transpose of a rank 1 array does nothing
v = np.array([1,2,3])
v

array([1, 2, 3])

In [104]:
v.T

array([1, 2, 3])

### Broadasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays of diff.
shapes when preforming aritmetic operations.
<br> <br>
Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple time to preform an operation on the larger aray. 
<br> <br>
For example, suppose we want to add a constant vector to each row of a matrix. 

In [110]:
np.array((4,3))

array([4, 3])

In [111]:
# We will add the vector v to each row of the matrix x,
# soring the results in matrix y

x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]])

In [112]:
v = np.array([1, 0, 1])

In [113]:
# creates an empty matrix with the same shape as x
y = np.empty_like(x)

In [114]:
y

array([[3761407486850185783, 8296241989623952945, 4189032028197581669],
       [3546415611097985570, 4122312523514391864, 4049691970969363257],
       [3833233122508497968, 7310315409782224180, 2466321564960910962],
       [8317341659774738793, 4189022137156394855, 8387229111175570210]])

In [118]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [115]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

In [116]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [117]:
x[0, : ] + v

array([2, 2, 4])

This works,however when the matrix `x` is very large, 
computing an explicit loop could be slow.
<br>
Cool trick: <br> <br>
We can see that adding the vector `v` to each row of the matrix `x` is equvalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, 
then preforming elementwise summpation of `x` and `vv`.

In [119]:
# we will add the vectors v to each row of the matrix x, 
# storing the results in the matrix y

x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9],
             [10,11,12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))

In [120]:
vv # `v` stacked four times

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [121]:
y = x + vv # Add x and vv elementwise!

In [122]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

Numpy broadcasting allows us to preform this computation without actually creating multiple copies of `v`!

In [123]:
y = x + v

In [124]:
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

wow!

The line `y = x + v` works even though `x` has shape `(4, 3)`
and `v` has shape `(3,)` due to broadcasting!
<br>
This line works as if `v` actually had shape `(4, 3)`, where each row was a copy of `v`
AND the sum was preformed elementwise!!!

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
<br>
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
<br>
3. The arrays can be broadcast together if they are compatible in all dimensions.
<br>
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
<br>

5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension
<br>
<br>
**Resource:** http://wiki.scipy.org/EricsBroadcastingDoc

In [128]:
# Compute outer product of vectors
v = np.array([1,2,3])
w = np.array([4,5])
print (v)
print(w)

[1 2 3]
[4 5]


In [126]:
# To ccompute an outer product, we first reshape v to be a column
# vector of shape (3, 1)
# Then we can broadcast it agianst w to yield 
# an output of shape ( 3, 2), which is the outer product of v and w


In [129]:
np.reshape(v, (3,1))

array([[1],
       [2],
       [3]])

In [127]:
np.reshape(v, (3,1)) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [130]:
x = np.array([[1,2,3],
             [4,5,6]])

In [132]:
# x has shape ( 2,3) and v has shape (3,) so they broadcast to (2,3)

In [133]:
print(x + v)

[[2 4 6]
 [5 7 9]]


In [134]:
# Add a vector to each column of a matrix 
# x has shape (2, 3) and w has shape (2,).

# If we transpose x then it has shape (3, 2)
# and can be broadcast agiasnt w to yiled a result of shape (3,2)
# Transposing this result yileds the final resul of shape (2,3)
# which is the matrix x with the vector w added to each col.


In [135]:
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [136]:
# Another solution is to reshape w to be a column vector of shape (2,1)
# We can then broadcast it directly agianst x to produce the same output!


In [140]:
w

array([4, 5])

In [142]:
np.reshape(w, (2,1))


array([[4],
       [5]])

In [138]:
x + np.reshape(w, (2,1))

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
# Multipying a matrix by a constant: 
# x has shape (2,3). Numpy treats sccalars as arrays of shape ();
# these can be broadcast together to shape (2,3)

In [143]:
print(x)

[[1 2 3]
 [4 5 6]]


In [144]:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
# Broadcasting typically makes your code more concise and faster.


### Numpy Reference
**Resource:** https://docs.scipy.org/doc/numpy/reference/

### Image Operations - using SciPy

In [151]:
!pip install scipy

In [155]:
import scipy # import imread, imsave, imresize 

In [ ]:
from matplotlib.pyplot import imread

In [ ]:
img = imread('assets/cat.jpg')

In [ ]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into a numpy array
img = imread('assets/cat.jpg')
print(img.dtype, img.shape)  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (300, 300))

# Write the tinted image back to disk
imsave('assets/cat_tinted.jpg', img_tinted)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

In [ ]:
import numpy as np
from scipy.misc import imread, imresize
import matplotlib.pyplot as plt

img = imread('assets/cat.jpg')
img_tinted = img * [1, 0.95, 0.9]

# Show the original image
plt.subplot(1, 2, 1)
plt.imshow(img)

# Show the tinted image
plt.subplot(1, 2, 2)

# A slight gotcha with imshow is that it might give strange results
# if presented with data that is not uint8. To work around this, we
# explicitly cast the image to uint8 before displaying it.
plt.imshow(np.uint8(img_tinted))
plt.show()
